export type ProjectRecord = {slug:string; href?:string; title:string; category:string; summary:string; overview:string; features:string[]; stack:string[]; flow:string[]; limits:string; sources:{label:string;href:string}[]; image?:string; imageAlt?:string; imageCaption?:string; gallery?:{src:string;alt:string;caption:string}[]; videos?:{src:string;poster:string;caption:string}[]; status:string; note?:string;};
const gh=(repo:string)=>({label:'Public source repository',href:`https://github.com/RoboX2020/${repo}`});
export const PROJECT_LIBRARY: ProjectRecord[] = [
{slug:'get-it-done',href:'/get-it-done',title:'Get Done',category:'Browser tools × motivation',status:'Open-source extension',summary:'Finish a homework question. Move to the next one. A picture unlocks as a small reward for getting it done.',overview:'A Chrome and Edge extension that pairs homework progress with a personal list of reward pictures. The panel waits for the homework page to mark a question done, then flashes the next picture when you move on.',features:['One picture per completed question.','Movable, resizable side panel.','Picture links and progress saved locally in the browser.'],stack:['JavaScript','Chrome / Edge','Browser extension'],flow:['Add your picture links.','Complete a homework question.','Move on to unlock the next picture.'],limits:'Installed unpacked from GitHub, not through an extension store. The action shots show a demo quiz, not a live graded assignment.',sources:[gh('get-it-done')],image:'/projects/9-get-done-flash.png',imageAlt:'Get Done side panel flashing a reward picture beside a completed demo quiz question',imageCaption:'The extension in action on a demo quiz.'},
{slug:'gotapri',title:'GoTapri',category:'Community × collaboration',status:'Project archive',summary:'A place for early-stage builders to find their people, form teams and give their ideas a public home.',overview:'GoTapri grew from a simple observation: people had ideas, but many were trying to build alone. The platform brought team formation, startup pages and collaborator discovery into one place. This archive keeps the project accessible from my portfolio after the original domain lease ended.',features:['Team formation and collaborator discovery for young founders.','Public startup pages to give an idea a place people can find and join.','A builder community around feedback, mentorship and making things together.'],stack:['Community platform','Team matching','Startup profiles'],flow:['A builder brings an idea or a skill.','A public project page makes the work discoverable.','People find teams and collaborators to move the work forward.'],limits:'This is a record of the platform, not a claim that every service described in its early pitch remains available. The original domain is not treated as a working demo. Community reach and launch metrics are omitted here rather than presented without context.',sources:[{label:'Original founder post · June 2025',href:'https://www.linkedin.com/posts/prajvalarora_tapri-teambuilding-teenpreneur-activity-7339727831645528065-dzdY'}]},
{slug:'air-guitar',title:'Air Guitar',category:'Music × embedded sensing',status:'Hardware prototype',summary:'Wrist motion becomes the trigger for a synthesized string. No physical guitar required.',overview:'Air Guitar connects an Arduino and inertial sensor to a Python audio engine. Wrist angle selects virtual strings; a strumming motion triggers notes generated with Karplus-Strong synthesis.',features:['Serial input from an Arduino-connected MPU6050 sensor.','Startup calibration for a neutral wrist position.','Open-E virtual strings selected by wrist angle.','Plucked-string synthesis mixed in a real-time sound callback.'],stack:['Arduino','MPU6050','Python','NumPy','sounddevice','pyserial'],flow:['Measure wrist angle and acceleration.','Send roll and force over USB serial.','Detect a string crossing with sufficient motion.','Generate and mix a plucked-string waveform.'],limits:'Requires the physical sensor setup and a local audio device. This review inspected code, not a fresh hardware run. No zero-latency or performance benchmark is claimed.',sources:[gh('Air-Guitar')]},
{slug:'caricature-drawing',title:'Caricature Drawing Robot',category:'Computer vision × motion',status:'Hardware prototype',summary:'Take an image, turn its contours into strokes, and give those strokes to a robot arm.',overview:'A Python pipeline maps image edges to a calibrated drawing area on a Dobot Magician Lite. The operator previews the paths before queued robot movements draw them on paper.',features:['Image loading and adjustable edge/detail processing.','Paper-corner and pen-height calibration.','Path preview before physical movement.','G-code generation and robot command control.'],stack:['Python','OpenCV','Dobot Magician Lite','Serial control'],flow:['Load a photograph or line-art image.','Extract edges, contours and drawing paths.','Map pixels into the calibrated paper area.','Preview the result, then run the robot.'],limits:'The repository includes hardware-control code; a physical drawing session was not run for this page. It is not a claim of autonomous caricature generation from every input or certified robot safety.',sources:[gh('caricature-drawing-robot')]},
{slug:'air-piano',title:'Air Piano',category:'Computer vision × sound',status:'Local prototype',summary:'A camera sees fingertips. A virtual keyboard turns their position into notes.',overview:'The virtuoso-piano repository combines MediaPipe hand landmarks, OpenCV video and a separate audio engine. It maps tracked fingertips into the keyboard interface rather than requiring a physical piano.',features:['Tracks up to two hands with a local MediaPipe hand-landmarker model.','Uses thumb and finger-tip coordinates in the virtual keyboard.','Separates vision processing from the audio engine.'],stack:['Python','OpenCV','MediaPipe','Audio samples'],flow:['Capture a webcam frame.','Detect hand landmarks and fingertip positions.','Map positions into the displayed keyboard.','Trigger local audio playback.'],limits:'Needs a webcam, the hand_landmarker.task model and local audio/sample setup. No latency, musical accuracy or installation success is claimed by this source review.',sources:[gh('virtuoso-piano')]},
{slug:'air-mouse',title:'Air Mouse',category:'Wearables × interaction',status:'Hardware prototype',summary:'An inertial sensor moves the cursor, with a hardware input for clicking.',overview:'The public Air-Mouse source pairs an Arduino sketch using an MPU9250 sensor with a Python serial listener. Sensor output is translated into mouse movement and left-click actions on the computer.',features:['Arduino reads motion data and a click input.','Serial messages carry X/Y motion and click state.','Python controls pointer motion and button presses through pynput.'],stack:['Arduino','MPU9250','Python','pynput','USB serial'],flow:['Read sensor values on the wearable.','Stream movement and click state over serial.','Scale the motion into pointer movement.','Press or release the mouse button from the input state.'],limits:'This is inertial wearable control, not eye-gaze tracking. Requires hardware and local pointer-control permissions.',sources:[gh('Air-Mouse')]},
{slug:'celialife',title:'CeliaLife',category:'Health records × software',status:'Application prototype',summary:'Organize medical documents and ask questions with the record as context.',overview:'CeliaLife is a full-stack personal health record application. Its repository includes authenticated document upload, storage metadata, OCR/text extraction and contextual AI chat.',features:['Organize uploaded PDF and image medical records.','Authenticated routes and document metadata.','Text extraction for document-grounded chat.','React interface backed by Express and a PostgreSQL/Drizzle data layer.'],stack:['React','TypeScript','Express','PostgreSQL','Drizzle ORM','OpenAI integration'],flow:['Sign in and upload a record.','Store the file and document metadata.','Extract text for the record context.','Use that context in chat assistance.'],limits:'Not medical advice, diagnosis or proof of clinical validation. No healthcare compliance or security certification is claimed. Requires configured infrastructure/API credentials; no public demo or patient data is exposed here.',sources:[gh('celia-life')]},
{slug:'kalki',title:'Kalki',category:'Civic ideas × community',status:'Application prototype',summary:'A place to raise problems, describe a goal and gather people around it.',overview:'The Kalki application implements a post-driven interface with demands, goals and a discussion drawer. Firebase authentication and a store layer support the community interactions.',features:['Create posts with a description, goal, demands and guiding tenets.','Authenticated user state.','Discussion drawer tied to individual posts.','A manifesto and seed-data flow in the prototype.'],stack:['React','TypeScript','Firebase'],flow:['Browse community posts.','Sign in before taking an authenticated action.','Create a post that describes the goal and needs.','Open the discussion attached to that post.'],limits:'Source review does not establish real community adoption or deployment status. The repository has demo/seed behavior, so example posts are not presented as real outcomes.',sources:[gh('kalki-app')]},
{slug:'dobot-plc',title:'Dobot + Opta PLC',category:'Industrial control × robot cells',status:'Hardware integration',summary:'Four arms, one sequence: sensor triggers and completion signals coordinate the line.',overview:'My team connected Dobot Magician Lite arms to an Arduino Opta PLC. A Python control layer teaches and queues the robot motions while the PLC links start/done signals into a staged process.',features:['Four-arm pick-and-place sequence described in the source.','IR proximity trigger and digital start/done handshakes.','Conveyor control and teach-pendant-style Python tools.','Separate PLC sketch and Dobot command-queue logic.'],stack:['Arduino Opta','C++','Python','Dobot DLL','Digital I/O'],flow:['A sensor triggers the first stage.','The PLC signals the robot to start.','The robot completes its taught motion and reports done.','The next stage begins through the PLC handshake.'],limits:'This is a prototype integration, not a claim of production throughput or certified industrial safety. No hardware run or wiring validation was performed for this page.',sources:[gh('dobot-opta-plc-automation')]},
{slug:'microtube-insertion',title:'Microtube Insertion System',category:'Aerospace × passive alignment',status:'Team hackathon prototype',summary:'Use geometry and vibration to address a bottleneck in heat-exchanger assembly.',overview:'The 2026 Well, Honey! team prototype explored microtube alignment and insertion using chamfered guides, controlled vibration and separation of the plates. The public team repository records third place at Honeywell x ASU Devils Invent.',features:['Cone-shaped/chamfered guides for tube alignment.','Controlled vibration to help tubes find their alignment.','Linear-actuator plate separation.','3D-printed prototypes documented with photos.'],stack:['Mechanical design','3D printing','Controlled vibration','Linear actuator'],flow:['Guide tubes toward the tubesheet with the plate geometry.','Use vibration to help alignment.','Insert the tubes without treating every placement as a separate robot task.','Separate the plates after insertion.'],limits:'The page documents a team prototype, not measured factory throughput. The RoboX2020 repository is a fork of Sameerjeet Singh Chhabra\'s team repository. Team: Prajval Arora, L Johnson, Toshan Jagani, Riya Mehta and Sameerjeet Singh Chhabra.',sources:[gh('microtube-insertion-system'),{label:'Original team repository',href:'https://github.com/Sjschhabra/microtube-insertion-system'}],image:'/projects/microtube.jpg',imageAlt:'Well, Honey! team presenting at the Honeywell hackathon'},
{slug:'esp-claw',title:'ESP-Claw Arduino Bridge',category:'Open source × embedded tools',status:'Open pull request',summary:'Give a small Arduino access to the agent workflow without asking it to run the whole stack.',overview:'PR #11 proposes an Arduino UNO compatibility layer for Espressif\'s ESP-Claw. A host-side bridge and natural-language shell communicate with peripheral firmware over serial.',features:['JSON commands over serial to the UNO.','GPIO, analog, servo and I2C operations in the proposed layer.','Host-side Python bridge.','Natural-language programming shell with provider integrations.'],stack:['Arduino UNO','Python','Serial JSON','ESP-Claw'],flow:['The host receives a CLI/API request.','The bridge sends a serial command.','UNO firmware operates the peripheral.','Results return to the host.'],limits:'The contribution is an open pull request, not a merged feature or endorsement by Espressif. No remote service credentials are included on this page.',sources:[{label:'Espressif pull request #11',href:'https://github.com/espressif/esp-claw/pull/11'}]},
{slug:'partyplay',title:'PartyPlay',category:'Games × shared screens',status:'Web prototype',summary:'A phone becomes the arcade controller. The room watches each turn on the big screen.',overview:'The current PartyPlay source is a queue-based arcade showcase. Players join by QR, wait their turn, and stream their game canvas to a host display. The older multiplayer/Kahoot-style version is kept in a backup folder.',features:['QR and room-code joining.','One active player with an automatic queue.','Six canvas arcade games.','Live JPEG frame relay and session hall of fame.'],stack:['Node.js','Express','Socket.IO','JavaScript','Canvas'],flow:['The host opens a room on the shared display.','Players join the queue from their phones.','The first player receives a turn.','Canvas frames and scores relay to the host; the next player follows.'],limits:'The host lobby was run locally for this page. No public hosted demo or network benchmark was verified. The repository describes roughly 8 fps frame streaming, not full-rate video. Current behavior is turn-based, not simultaneous multiplayer.',sources:[gh('partyplay')]},
{slug:'aether',title:'Aether',category:'Gesture × audiovisual synthesis',status:'Browser prototype',summary:'Move your hands in front of a webcam to shape sound and light.',overview:'Aether combines MediaPipe hand tracking, Web Audio synthesis and canvas visuals. The hands become a control surface for an audiovisual instrument in the browser.',features:['Tracks two hands from webcam landmarks.','Finger position and pinch state map into audio controls.','Oscillator voices and audio effects.','Particle and hand-skeleton canvas visuals.'],stack:['JavaScript','MediaPipe','Web Audio','Canvas'],flow:['Allow camera access and initialize hand tracking.','Classify the left and right hands.','Map landmark positions into sound parameters.','Draw responsive particles and hand geometry.'],limits:'No physical-camera play test was run for this page. Browser permissions, model downloads and audio activation are required. No claim of accessibility validation or calibrated musical control.',sources:[gh('aether')]},
{slug:'esp32-ai-robot',title:'ESP32 AI Robot',category:'Embedded displays × conversation',status:'Hardware prototype',summary:'A tiny OLED face, a local web controller and AI-connected interactions.',overview:'The ESP32-C3 project uses an OLED and buzzer with a browser controller. The source includes expressive eyes, text modes, WebSockets and an OpenAI integration for generated responses.',features:['OLED eye animations and text display modes.','Local browser controller with speech input.','WebSocket communication.','Image upload and code paths for games/music on the device.'],stack:['ESP32-C3','C++','SSD1306 OLED','WebSockets','Browser speech input'],flow:['Serve the control interface from the device.','Collect a user request in the browser.','Send device commands over the local connection.','Render text, animations or sound on the hardware.'],limits:'Requires hardware, local network setup and API configuration. This page does not demonstrate that arbitrary generated programs are safe to execute or that the device works offline with AI. No live hardware session was tested.',sources:[gh('esp32-ai-robot')]},
{slug:'life',title:'LIFE',category:'Computer vision × emergency signals',status:'Experimental prototype',summary:'Explore how a camera pipeline can turn detected events into an alert workflow.',overview:'LIFE (Last-minute Intervention, Full Existence) is an experimental Python camera-processing project with model loading, event fusion, annotations and alarms. It explores fall/fire/threat detection and downstream notifications.',features:['Camera capture and a model-processing pipeline.','Event fusion and image annotation.','Local alarm and notification code paths.','Web/API components in the source.'],stack:['Python','Computer vision','Event fusion','Alert pipeline'],flow:['Read a camera frame.','Run configured detection models.','Combine detections into an event assessment.','Annotate the result and trigger the configured alarm path.'],limits:'Not an emergency-response service or a reliable safety system. README accuracy/speed/dispatch claims were not independently validated. Do not rely on this prototype for medical, security or fire protection. No live alerts were sent.',sources:[gh('LIFE-system')]},
{slug:'skydrift',title:'SkyDrift Demo Adaptation',category:'Flight simulation × phone interaction',status:'Adapted open-source demo',summary:'Bring people into a shared flight-sim demo with QR joining and phone views.',overview:'This is my adaptation of the open-source SkyDrift flight simulator, originally from hambaloch/skydrift. The demo work explored QR joining, phone cockpit/tail views and shared flight interaction.',features:['QR-linked phone joining for the demo.','Cockpit and tail viewpoints.','Phone-control interface and multiplayer demo work.'],stack:['TypeScript','Web flight simulation','QR joining'],flow:['Open the host game.','Join from a phone using its QR link.','Use the phone interface while the shared world runs.'],limits:'Explicitly a fork/adaptation, not a claim of originating the full simulator. Current public hosting is not verified here, so this page links source rather than offering an untested live demo.',sources:[gh('skydrift'),{label:'Original SkyDrift project',href:'https://github.com/hambaloch/skydrift'}]},
];
const records: [string,string,string,string,string][] = [
['ar-speech-therapy','AR Speech Therapy','Wearables × speech guidance','A wearable integration project combining local compute, stereo vision and an AR display.','My resume records work on a Jetson Nano-based AR-assisted speech therapy device at Barrow, with local inference, stereo vision and hardware/real-time guidance integration.'],
['stellantis-cell','Stellantis Dual-URSe Cell','Robot cells × digital twins','A demonstrator linking a physical robot cell with its simulation workflow.','The project involved dual URSe cobots, end-effectors, machine vision, cell networking, Isaac Sim validation and commissioning for an ASU/Wandelbots demonstrator.'],
['manufacturing-line','Manufacturing Line Replica','Automation × material flow','An industrial-cell learning build that coordinates arms, conveyors, sensors and PLC logic.','My current resume records integration work with UR5, UR3, JAKA and Dobot arms, PLCs, conveyors, sensors and vision to replicate automated material flow.'],
['unitree-go2','Unitree Go2 in Simulation','Robotics × perception','Explore quadruped control and sensor views in a digital-twin environment.','My Go2 lab exploration used a PyBullet simulation to observe leg motion, sensor views and obstacle interaction. Depth, RGB and lidar panels make the simulated surroundings visible alongside the robot.'],
['jet-cooling','Jet Cooling Concept','Aerospace × thermodynamics','A team hackathon concept exploring bleed-air exhaust for jet cooling.','The existing portfolio records the 2025 Honeywell team project: a jet-engine heat-exchange/cooling concept using bleed-air exhaust. The later 2026 microtube manufacturing project is documented separately.'],
['riverside-data-centers','Riverside Data Centers','Climate × compute','Research into dam-based data-center cooling and power.','My existing portfolio and resume describe research into data centers at dams, combining cooling and power-generation ideas. This page preserves the research topic; the underlying paper text is not yet available in this archive.'],
['faith-labs','FAITH Labs','Education × hands-on robotics','Build the lab, the curriculum and the confidence to make something.','My resume records founding school robotics labs in Kanpur, procuring kits, designing curriculum, teaching students and coaching competition teams.'],
['robotics-championship','Competition Robot','Constraint × mechanics','An omnidirectional vehicle with a robot arm and phone-based control.','The existing portfolio records an omnidirectional competition robot with a mounted arm and a local Wi-Fi server for phone control. This archive preserves the build concept without adding a new performance claim.'],
['arms-asu','A R M S at ASU','Flight × student engineering','Software and operations across student engineering projects.','My resume records treasurer, marketing and software-project responsibilities in A R M S, alongside engineering work around aircraft, boats and FPV vehicles. This is an ongoing-work record, not a standalone product release.'],
['paper-tic-tac-toe','Tic-Tac-Toe on Paper','Vision × physical games','A robot arm sees a mark and draws its move.','The existing portfolio describes a paper tic-tac-toe project using vision and inverse kinematics to turn game state into physical drawing. The implementation source has not yet been located.'],
['spider-robot','Language-Controlled Spider Robot','Natural language × motion','Explore the path from a spoken request to a multi-leg robot action.','The existing portfolio describes parsing natural-language requests into multi-leg motion. The source and physical test records have not yet been located, so this entry remains a concise project note.'],
['vibeverse','VibeVerse','Marketplace × creative software','A marketplace concept for sharing AI-generated projects.','The existing portfolio describes a marketplace for builders to share and discover AI-generated projects. The old domain could not be verified as a working site during this review.'],
['euler-ai','Euler Ai','Math × visual explanation','Turn a written mathematical idea into an animation.','The existing portfolio describes a text-to-math-animation agent intended for educators. The implementation repository, evaluation and runnable demo have not yet been located.'],
];
PROJECT_LIBRARY.push(...records.map(([slug,title,category,summary,overview])=>({slug,title,category,summary,overview,status:'Project note',features:[],stack:[],flow:[],limits:'This is a short project note, not a full technical case study. Build photos, implementation details and measured results are not included yet.',sources:[],note:'More build material is being collected.'})));

const media: Record<string, ProjectRecord['gallery']> = {
'dobot-plc': [
 {src:'/projects/dobot-setup.png',alt:'Dobot arm, conveyor and control panel',caption:'Setup image included in the public Dobot repository. It shows a one-arm station, not the full four-arm line.'},
 {src:'/projects/dobot-monitor.png',alt:'System monitor interface in the repository',caption:'System monitor image included in the public source repository.'}
],
'microtube-insertion': [{src:'/projects/microtube-concept.png',alt:'Chamfered tube-guide geometry',caption:'Guide-plate concept from the team repository.'}],
'aether': [{src:'/projects/aether-screen.png',alt:'Aether instrument start screen',caption:'Start screen captured from a local run of the public source. Webcam gesture play was not tested.'}],
'partyplay': [{src:'/projects/partyplay-host.png',alt:'PartyPlay host lobby with QR code, queue and game choices',caption:'Host lobby captured from a local run. The QR code points to that local test, not a public demo.'}],
'unitree-go2': [{src:'/projects/go2-simulation.png',alt:'Go2 PyBullet simulation with depth, RGB and lidar panels',caption:'Screenshot extracted from my Go2 lab report. This view is PyBullet, not Isaac Sim.'}],
'riverside-data-centers': [{src:'/projects/river-paper-excerpt.png',alt:'Title and introduction from my data-center robotics paper',caption:'Title and introduction excerpt from my ASU paper, Increasing Efficiency of Data Centers through Robotics.'}]
};
for (const p of PROJECT_LIBRARY) { p.gallery=media[p.slug]; if(p.slug==='microtube-insertion') p.imageCaption='Team presentation photo from the public project repository.'; }
const river=PROJECT_LIBRARY.find(p=>p.slug==='riverside-data-centers')!;
river.overview='My earlier research explored data centers near dams, using hydropower and reservoir cooling. A later ASU paper, Increasing Efficiency of Data Centers through Robotics, revisits that idea through thermal sensing, inspection, maintenance and digital-twin literature.';
river.limits='Research and literature review, not a built data center or a measured cooling-efficiency result. The excerpt is from my own introduction; the reviewed robotics systems belong to the cited researchers.';
river.note='The original dam-siting paper is still being located. The excerpt here is from the later robotics-focused paper.';

const go2=PROJECT_LIBRARY.find(p=>p.slug==='unitree-go2')!;
go2.title='Unitree Training in Isaac Sim';
go2.category='Physical AI × simulation';
go2.status='Training exploration';
go2.summary='Train a quadruped in simulation, with walking and flipping as the target skills.';
go2.overview='My Unitree work includes Isaac Sim training aimed at teaching the robot to walk and flip. The clips below show the simulation work, including a parallel quadruped scene. A separate Go2 lab-report image records a PyBullet exploration with depth, RGB and lidar panels; it is not an Isaac Sim screenshot.';
go2.stack=['Isaac Sim','Quadruped training','PyBullet exploration'];
go2.features=['Isaac Sim training aimed at walking and flipping.','Parallel quadruped simulation visible in the training clip.','Separate PyBullet lab exploration with depth, RGB and lidar views.'];
go2.limits='The clips document simulation work, not a benchmarked training result. Walking and flipping are the training goals; successful physical-robot deployment or sim-to-real transfer is not claimed here.';
go2.note='The simulation clips were provided from my own project records. The lab-report image below is labeled separately to preserve which simulator it shows.';
go2.videos=[
 {src:'/projects/unitree-motion.mp4',poster:'/projects/unitree-motion-poster.jpg',caption:'Unitree simulation clip. Walking and flipping are the training goals, not a measured success claim.'},
 {src:'/projects/unitree-training.mp4',poster:'/projects/unitree-training-poster.jpg',caption:'Isaac Sim training scene with multiple simulated quadrupeds. Recorded from the training interface.'}
];

// Real project captures collected October 7, 2026. No stock or generated images.
const capturedMedia: Record<string, {src:string;alt:string;caption:string}> = {
 'air-guitar': {src:'/projects/3-air-guitar-demo.jpg',alt:'Prajval demonstrating the wired Air Guitar sensor',caption:'Still from my Air Guitar demonstration video on LinkedIn.'},
 'air-mouse': {src:'/projects/4-air-mouse-demo.jpg',alt:'Air Mouse breadboard and physical click control',caption:'Still from my Air Mouse demonstration video on LinkedIn.'},
 'caricature-drawing': {src:'/projects/6-caricature-code-output.png',alt:'Edge paths generated from a portrait by the drawing robot code',caption:'Actual image-processing output from a local run using my portrait: 104 paths. The robot arm was not connected or run.'},
 'celialife': {src:'/projects/7-celia-landing.png',alt:'CeliaLife logged-out landing interface',caption:'Logged-out interface captured from a local run. No medical records or personal uploads are shown; interface copy is not independent verification of its claims.'},
 'esp32-ai-robot': {src:'/projects/8-esp32-controller.png',alt:'ESP32 robot browser controller with command and mood controls',caption:'The repository browser controller served locally. It is waiting for a hardware connection; no OLED, AI or speech session was run.'},
 'skydrift': {src:'/projects/14-skydrift-host.png',alt:'SkyDrift local host screen with a three-dimensional island and join code',caption:'Host screen captured from a local client and server run. The join code belongs to that local test, not a public hosted room.'},
 'manufacturing-line': {src:'/projects/13-manufacturing-showcase.jpg',alt:'Manufacturing project team presenting at the ASU Innovation Showcase',caption:'Project-team photo from Sara Doyle’s public RAS 102 manufacturing-line post. This documents the team showcase, not every robot named in this wider work record.'},
 'life': {src:'/projects/12-life-console.png',alt:'LIFE console interface waiting for its camera and event connection',caption:'Console interface served locally from the repository, without a connected detector or live camera. No detection, dispatch or performance result is demonstrated.'}
};
for(const p of PROJECT_LIBRARY){const m=capturedMedia[p.slug];if(m)p.gallery=[...(p.gallery||[]),m];}

const tapri=PROJECT_LIBRARY.find(p=>p.slug==='gotapri')!;
tapri.gallery=[{src:'/projects/10-gotapri-archive.png',alt:'GoTapri archived landing page with project and sign-in links',caption:'The archived go-tapri.vercel.app landing page captured October 7. This shows the interface, not verified current community activity.'}];

const kalki=PROJECT_LIBRARY.find(p=>p.slug==='kalki')!;
kalki.gallery=[{src:'/projects/11-kalki-landing.png',alt:'Kalki landing interface with Gather the Embers headline',caption:'Genuine local front-end capture with external API traffic blocked and placeholder local configuration. No live posts, login, database seed or AI calls were made.'}];
const extraSources:Record<string,{label:string;href:string}>={
 'air-guitar':{label:'Air Guitar demo video',href:'https://www.linkedin.com/posts/prajvalarora_guitar-arduino-tech-ugcPost-7404269130801012736-yHCj/'},
 'air-mouse':{label:'Air Mouse demo video',href:'https://www.linkedin.com/posts/prajvaldesignsmachines_ai-tech-innovation-activity-7399010092685139968-g50Q'},
 'manufacturing-line':{label:'Team manufacturing showcase post',href:'https://www.linkedin.com/posts/sara-doyle-285458382_robotics-automation-plc-activity-7463790862519545856-TjTP'},
 'gotapri':{label:'Archived landing interface',href:'https://go-tapri.vercel.app'}
};
for(const p of PROJECT_LIBRARY){if(extraSources[p.slug])p.sources.push(extraSources[p.slug]);}

const arms=PROJECT_LIBRARY.find(p=>p.slug==='arms-asu')!;
arms.gallery=[{src:'/projects/5-arms-mark.png',alt:'A R M S robotics organization mark',caption:'Organization mark included in my public drawing-robot repository. This is branding, not a photo of a completed robot.'}];

PROJECT_LIBRARY.splice(1,0,{
 slug:'get-done-code', title:'Get Done for Code', category:'Developer tools × motivation', status:'Extension, testing build 0.1.0',
 summary:'Set your own coding goals. Hit one and a reward image you picked unlocks.',
 overview:'The follow-up to Get Done, built for the editor instead of the homework page. It is a VS Code extension that also runs in Cursor and Antigravity, since all three are VS Code based, from one package. You choose what counts as progress in a setting called getDone.criteria. Each time you hit a goal, a side panel opens beside your code and shows the next reward image from your own list. Nothing is bundled or hosted: the images load straight from links you add, one at a time, in order, then cycle. Counts stay on your machine. Only the GitHub goal makes a network call, to GitHub\'s API for your own contribution count. The extension never reads or sends your code.',
 features:['Lines goal: a reward every N new lines typed. Undo and redo are ignored, and a huge paste counts as at most 200 lines per change.','Saves goal: a reward every N file saves.','Minutes goal: a reward every N minutes of active typing.','GitHub goal: one reward on each day you make a GitHub contribution, checked through VS Code\'s built-in GitHub sign-in with read:user scope only, every 15 minutes by default.','A status bar item showing progress, plus commands to add a reward link, preview the next reward, check GitHub now, and reset.','Rewards open in a webview that only allows https images.'],
 stack:['TypeScript','VS Code Extension API','GitHub API','Webview'],
 flow:['Set goals, for example { "type": "lines", "every": 100 } and { "type": "github" }.','Add your own https image links with "Get Done: Add Reward Image Link".','Write code. The status bar tracks progress toward each goal.','When one is hit, the reward panel opens beside your editor with the next image.'],
 limits:'Version 0.1.0, installed from a packaged .vsix for testing and not yet on the Marketplace. The screenshot renders the extension\'s own reward-panel markup in a browser with a sample reward image, since the panel is a plain HTML view; it is not a capture of the editor window. It is open source under the MIT license.',
 image:'/projects/12-get-done-code-reward.png', imageAlt:'The reward panel: "Goal hit! Reward #1" above a reward image on a dark editor background', imageCaption:'The reward panel, using the extension\'s own markup with a sample image from the Get Done demo.',
 sources:[{label:'Source repository on GitHub',href:'https://github.com/RoboX2020/get-done-code'},{label:'Get Done, the browser extension it grew from',href:'https://github.com/RoboX2020/get-it-done'}]
} as ProjectRecord);
